name: Continuous Integration
on:
  pull_request:  # Aciona para pull requests
  push:          # Aciona para pushs
    branches:
      - 'feature/*'  # Isso significa qualquer branch
jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '22'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn clean install

      - name: Build and test
        run: mvn clean test

      - name: Run Cucumber Tests
        run: mvn -Dtest=runner.TestRunner test

      - name: List test files
        run: ls -R src/test

